### ISSUE TITLE
Make it work for complex enums

### ISSUE THREAD

**Issue by bestouff** [cofinite/enum_properties#1]
Would it be possible to make it work for enum which contain data ? That would give the best of both worlds.

**Comment by cofinite** [comment]
> 
> 
> Would it be possible to make it work for enum which contain data ? That would give the best of both worlds.

This is something I've considered and is definitely possible. I'll see when I have time to work on it.

**Comment by bestouff** [comment]
First step would be to convert the `match` in the `Deref` `impl` to a const array lookup:
```rust
        impl core::ops::Deref for $Enum {
            type Target = $EnumProperties;
            fn deref(&self) -> &Self::Target {
                const PROPERTIES: [$EnumProperties; 3] = [
                    $($EnumProperties {
                        $($field: $value),* $(, .. $default)?
                    }),*
                ];
                &PROPERTIES[*self as usize]
            }
        }
```

**Comment by Tamschi** [comment]
That won't work, the tag isn't actually defined to be the first byte. See for example `Option<NonZeroU8>` as counter-example.

Using a match statement is fine (and probably the only way to do this, really) even for enums that carry data.

**Comment by bestouff** [comment]
Well `Enum as usize` is the standard way to get to the tag, but you're right it only works for simple (data-less) enums.

**Comment by cofinite** [comment]
I'm working on it now, will be updating later today.

**Comment by cofinite** [comment]
New version is now up on crates.io, and the new examples showcase the syntax. Thanks to @Tamschi for the PR!
